sudo: false
dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install flake8
script:
  - flake8 flask_slacksigauth
  - py.test --cov-report= --cov=flask_slacksigauth tests
after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION
